language: python
python:
  - 2.6
  - 2.7
  - 3.3
install:
  - pip install coverage flake8 pelican==$PELICAN_VERSION jinja-ab=$JINJA_AB_VERSION
script:
  - ./test.sh
env:
  - PELICAN_VERSION=3.6.3
  - JINJA_AB_VERSION=0.2.1

