env:
- _JINJA_AB=0.3.0 _PELICAN=3.6.3
- !!python/unicode '_JINJA_AB=0.3.0 _PELICAN=3.7.0'
install:
- pip install coverage flake8 Markdown pelican==$_PELICAN jinja-ab==$_JINJA_AB
language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
script:
- ./test.sh
